version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: book_coach
    ports:
      - "3308:3306"
  app:
    image: luzu4/bookcoachbe:latest
    environment:
      spring.datasource.url: jdbc:mysql://mysql-development:3306/book_coach
      SECRET_KEY: "4528482B4D6251655368566D597133743677397A24432646294A404E63526655"
      MYSQLDB_USER: root
      MYSQLDB_PASSWORD: helloworld
      MYSQL_URL: jdbc:mysql://localhost:3306/book_coach
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: luz@gmail.com
      MAIL_PASSWORD: example
    ports:
      - "8080:8080"
    depends_on:
      - mysql-development
  
